# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a8f8c6bc53c06dbf54fad4f3908f9974"
name = "recommendation-app"
handle = "recommendation-app-9"
application_url = "https://babes-elvis-desktop-catalyst.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "arwin-lb.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://babes-elvis-desktop-catalyst.trycloudflare.com/auth/callback",
  "https://babes-elvis-desktop-catalyst.trycloudflare.com/auth/shopify/callback",
  "https://babes-elvis-desktop-catalyst.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
